name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
      - run: docker build . --file Dockerfile --tag alexweininger/remotion-server:main
   
      - uses: docker/login-action@v1
      - name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - run: docker push alexweininger/remotion-server:main
      - name: Push to registry
        
